declare const process: {
  env: Record<string, string | undefined> & {
    EXPO_PUBLIC_APP_ENV?: string;
    EXPO_PUBLIC_SUPABASE_URL?: string;
    EXPO_PUBLIC_SUPABASE_ANON_KEY?: string;
    EXPO_PUBLIC_CLOUDINARY_CLOUD_NAME?: string;
    EXPO_PUBLIC_CLOUDINARY_UPLOAD_PRESET?: string;
    EXPO_PUBLIC_CLOUDINARY_UPLOAD_FOLDER?: string;
    EXPO_PUBLIC_GOOGLE_MAPS_API_KEY?: string;
    EXPO_PUBLIC_GOOGLE_MAPS_GEOCODING_API_URL?: string;
    EXPO_PUBLIC_GOOGLE_MAPS_PLACES_API_URL?: string;
    EXPO_PUBLIC_GOOGLE_MAPS_DIRECTIONS_API_URL?: string;
    EXPO_PUBLIC_AZURE_TRANSLATOR_ENDPOINT?: string;
    EXPO_PUBLIC_AZURE_TRANSLATOR_KEY?: string;
    EXPO_PUBLIC_AZURE_TRANSLATOR_REGION?: string;
    EXPO_PUBLIC_AZURE_TRANSLATOR_DEFAULT_FROM?: string;
    EXPO_PUBLIC_AZURE_TRANSLATOR_DEFAULT_TO?: string;
    EXPO_PUBLIC_GROQ_API_KEY?: string;
    EXPO_PUBLIC_GROQ_BASE_URL?: string;
    EXPO_PUBLIC_GROQ_MODEL?: string;
  };
};
